common/models/Textpage.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Textpage as BaseTextpage;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "textpage".
 */
class Textpage extends BaseTextpage
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                    'immutable' => true
                ],
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                  # custom validation rules
             ]
        );
    }
    
    public static function liLink($id, $class) {
        $model = Textpage::findOne($id);

        if ($_SERVER['REQUEST_URI'] == '/'.$model->alias) {
            $active = ' class="active"';
        } else {
            $active = '';
        }

        $name = '';
        if (Yii::$app->language == 'en') {
            $name = $model->en_name;
        } else {
            $name = $model->name;
        }

        return '<li'.$active.'><a href="/'.$model->alias.'" class="'.$class.'"><span>'.$name.'</span></a></li>';
    }
}

backend/controllers/TextpageController.php
<?php

namespace backend\controllers;

use common\models\Textpage;
use yii\filters\AccessControl;

/**
* This is the class for controller "TextpageController".
*/
class TextpageController extends \backend\controllers\base\TextpageController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actionCreate()
    {
        $model = new Textpage;

        try {
            if ($model->load($_POST) && $model->save()) {
                if ($_POST['mode'] == 'justSave') {
                    return $this->redirect(['update', 'id' => $model->id]);
                } else {
                    return $this->redirect(['index']);
                }
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            if ($_POST['mode'] == 'justSave') {
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                return $this->redirect(['index']);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
}

frontend/controllers/NewsController.php
<?php
namespace frontend\controllers;

use common\models\News;
use Yii;
use yii\web\Controller;


class NewsController extends BaseController
{
    public function actionIndex($alias)
    {
        $this->layout = 'textpage';
        $model = News::find()->where(['alias' => $alias])->one();
        return $this->render('index', ['model' => $model]);
    }
}

frontend/controllers/TextpageController.php
<?php
namespace frontend\controllers;

use common\models\News;
use common\models\Textpage;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class TextpageController extends BaseController
{
    public function actionIndex($alias)
    {
        $this->layout = 'textpage';
        $view = '';
        $model = Textpage::find()->where(['alias' => $alias])->one();

        switch($model->id) {
            case 1: {
                $page = (!empty($_GET['page']))? $_GET['page']: 1;
                $limit = 12;
                $offset = ($page == 1)? 0 : $page * $limit - $limit;
                $news = News::find()
                    ->limit($limit)
                    ->offset($offset)
                    ->orderBy(['date' => SORT_DESC])
                    ->all();

                return $this->render('news', [
                    'model' => $model,
                    'news' => $news,
                    'page' => $page,
                    'limit' => $limit,
                ]);
                break;
            }
            case 2: $view = 'vacancy';break;
            case 3: $view = 'contacts';break;
            case 4: $view = 'company';break;
            case 5: $view = 'services';break;
            case 6: $view = 'clients';break;
        }

        return $this->render($view, ['model' => $model]);
    }
}

frontend/views/textpage/clients.php
<?php
use common\models\Client;

if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}

?>
<div class="mainSection company">
    <div class="container">
        <div class="header"><span><?=(empty($seoH1)) ? $name : $seoH1 ?></span></div>
        <div class="clients__inner">
            <?php foreach(Client::find()->orderBy(['sortOrder' => SORT_ASC])->all() as $client) {
                if (Yii::$app->language == 'en') {
                    $name = $client->name;
                    $introtext = $client->en_introtext;
                    $text = $client->en_text;
                    $queries = $client->en_queries;
                } else {
                    $name = $client->name;
                    $introtext = $client->introtext;
                    $text = $client->text;
                    $queries = $client->queries;
                }
                ?>
                <div class="clients__item">
                    <a href="http://<?=$name?>" target="_blank" class="clients__itemImage" style="background-image: url(<?=$client->image?>);"></a>
                    <a href="http://<?=$name?>" target="_blank" class="clients__itemName"><span><?=$name?></span></a>
                    <div class="clients__itemText"><?=$introtext?></div>
                </div>
            <?php } ?>
        </div>
        <br>
        <br>
        <br>
        <br>
        <div class="company__hr"></div>
        <?=$this->render('@frontend/views/blocks/mainForm', ['class' => ' mainForm_company'])?>
        <br>
        <br>
    </div>
</div>

frontend/views/textpage/company.php
<?php

if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}
?>
<div class="mainSection company">
    <div class="container">
        <div class="header"><span><?=(empty($seoH1)) ? $name : $seoH1 ?></span></div>
        <div class="company__text">
            <?=Yii::t('translate', 'aboutContent')?>
        </div>
        <div class="company__hr"></div>
        <div class="company__faces">
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face1.png);"></div>
                <div class="company__faceName">Екатерина Власова</div>
                <div class="company__faceFunction">Project-manager</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face2.png);"></div>
                <div class="company__faceName">Александр Пронин </div>
                <div class="company__faceFunction">Project-менеджер</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face3.png);"></div>
                <div class="company__faceName">Ольга Короленко</div>
                <div class="company__faceFunction">SEO-оптимизатор</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face4.png);"></div>
                <div class="company__faceName">Петр Коротков</div>
                <div class="company__faceFunction">SEO-оптимизатор</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face5.png);"></div>
                <div class="company__faceName">Максим Прохоров</div>
                <div class="company__faceFunction">SEO-оптимизатор</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage" style="background-image: url(/img/face6.png);"></div>
                <div class="company__faceName">Вакансия </div>
                <div class="company__faceFunction">SEO-оптимизатор</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage"></div>
                <div class="company__faceName">Сергей Стригунков </div>
                <div class="company__faceFunction">Генеральный директор</div>
            </div>
            <div class="company__face">
                <div class="company__faceImage"></div>
                <div class="company__faceName">Никита Морозенко</div>
                <div class="company__faceFunction">Исполнительный директор</div>
            </div>
        </div>
        <div class="company__hr"></div>
        <div class="adv">
            <div class="adv__inner">
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa1.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv1h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv1t')?></div>
                </div>
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa2.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv2h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv2t')?></div>
                </div>
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa3.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv3h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv3t')?></div>
                </div>
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa4.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv4h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv4t')?></div>
                </div>
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa5.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv5h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv5t')?></div>
                </div>
                <div class="adv__item">
                    <div class="adv__itemImage" style="background-image: url(/img/aaa6.png);"></div>
                    <div class="adv__itemHeader"><?=Yii::t('translate', 'adv6h')?></div>
                    <div class="adv__itemText"><?=Yii::t('translate', 'adv6t')?></div>
                </div>
            </div>
        </div>
        <div class="company__hr"></div>
        <?=$this->render('@frontend/views/blocks/mainForm', ['class' => ' mainForm_company'])?>
        <br>
        <br>
    </div>
</div>

frontend/views/textpage/contacts.php
<?php
if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}
?>
<div class="map" onselectstart="return false" onmousedown="return false">
    <div id="map"></div>
    <div class="header">
        <div class="container">
            <span><?=(empty($seoH1)) ? $name : $seoH1 ?></span>
        </div>
    </div>
    <?=$this->render('@frontend/views/blocks/contactsMap')?>
</div>
<?=$this->render('@frontend/views/blocks/mainForm')?>
<?=$this->render('@frontend/views/blocks/mapTop', ['class' => 'map__top map__top_2'])?>

frontend/views/textpage/news.php
<?php
use common\models\News;
use yii\imagine\Image;

if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}
?>
<div class="mainSection">
    <div class="container">
        <div class="header"><span><?=(empty($seoH1)) ? $name : $seoH1 ?></span></div>
        <div class="news__inner">
            <?php foreach($news as $news_item) {
                if (Yii::$app->language == 'en') {
                    $name = $news_item->en_name;
                    $introtext = $news_item->en_introtext;
                } else {
                    $name = $news_item->name;
                    $introtext = $news_item->introtext;
                }
                ?>
                <a href="<?=\yii\helpers\Url::to(['news/index', 'alias' => $news_item->alias])?>" class="news__item">
                    <?php
                    $filename = explode('.', basename($news_item->image));
                    $thumbPath = '/uploads/thumbs/'.$filename[0].'-278-278.jpg';
                    Image::thumbnail('@www' . $news_item->image, 278, 278)
                        ->save(Yii::getAlias('@www'.$thumbPath), ['quality' => 80]);
                    ?>
                    <span class="news__itemLeft" style="background-image: url(<?=$thumbPath?>);"></span>
                    <span class="news__itemRight">
                        <span class="news__itemDate"><?=date('d.m.Y', $news_item->date)?></span>
                        <span class="news__itemHeader"><?=$name?></span>
                        <span class="news__itemText"><?=$introtext?></span>
                    </span>
                </a>
            <?php } ?>
        </div>
        <?=News::pagination(News::find()->count(), $page, $limit)?>
    </div>
</div>

frontend/views/textpage/services.php
<?php
if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}
?>
<div class="mainSection company">
    <div class="container">
        <div class="header"><span><?=(empty($seoH1)) ? $name : $seoH1 ?></span></div>
        <div class="light text-center" style="margin: 20px 0;font-size: 22px;color: #fff;"><?=Yii::t('translate', 'serh')?></div>
        <div class="usluga__tabs">
            <div class="usluga__tab"><?=Yii::t('translate', 'sert1')?></div>
            <div class="usluga__tab"><?=Yii::t('translate', 'sert2')?></div>
        </div>
        <div class="company__hr"></div>
        <div class="usluga__contents">
            <div class="usluga__content">
                <div class="company__text">
                    <div class="usluga__header"><?=Yii::t('translate', 'serit1h')?></div>
                    <?=Yii::t('translate', 'serit1t')?>
                </div>
                <div class="usluga__steps">
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst1')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst1h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst1t')?></div>
                    </div>
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst2')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst2h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst2t')?></div>
                    </div>
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst3')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst3h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst3t')?></div>
                    </div>
                </div>
            </div>
            <div class="company__hr"></div>
            <div class="usluga__content">
                <div class="company__text">
                    <div class="usluga__header"><?=Yii::t('translate', 'serit2h')?></div>
                    <?=Yii::t('translate', 'serit2t')?>
                </div>
                <div class="usluga__steps">
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst1')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst1h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst1t')?></div>
                    </div>
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst2')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst2h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst2t')?></div>
                    </div>
                    <div class="usluga__step">
                        <div class="usluga__stepNumber"><?=Yii::t('translate', 'serst3')?></div>
                        <div class="usluga__stepHeader"><?=Yii::t('translate', 'serst3h')?></div>
                        <div class="usluga__stepText"><?=Yii::t('translate', 'serst3t')?></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="usluga__text"><?=Yii::t('translate', 'serbottom')?></div>
        <div class="company__hr"></div>
        <?=$this->render('@frontend/views/blocks/mainForm', ['class' => ' mainForm_company'])?>
        <br>
        <br>
    </div>
</div>

frontend/views/textpage/vacancy.php
<?php
if (Yii::$app->language == 'en') {
    $seoTitle = $model->en_seo_title;
    $seoDescription = $model->en_seo_description;
    $seoKeywords = $model->en_seo_keywords;
    $seoH1 = $model->en_seo_h1;

    $name = $model->en_name;
} else {
    $seoTitle = $model->seo_title;
    $seoDescription = $model->seo_description;
    $seoKeywords = $model->seo_keywords;
    $seoH1 = $model->seo_h1;

    $name = $model->name;
}
?>
<div class="mainSection">
    <div class="container">
        <div class="header"><span><?=(empty($seoH1)) ? $name : $seoH1 ?></span></div>
        <div class="light text-center" style="font-size: 18px;color: #fff;">
            <p>Мы всегда рады видеть в нашем коллективе профессионалов<br>
                в различных сферах рынка интернет-маркетинга и специалистов<br>
                других направлений — квалифицированных, целеустремлённых,<br>
                энергичных, уверенных в своём успехе людей.</p>
            <p>Мы ждём в нашу команду молодых специалистов, обладающих<br>
                профессиональным и личным потенциалом и желанием<br>
                развиваться вместе с нами.</p>
        </div>
        <div class="vacancy">
            <div class="vacancy__header">SEO-оптимизатор</div>
            <div class="vacancy__inner">
                <div class="vacancy__item">
                    <div class="vacancy__itemHeader">Должностные обязанности:</div>
                    <ul>
                        <li>Знание html, понимание принципов
                            работы php, умение разобраться в коде;</li>
                        <li>Аудит сайтов, написание рекомендаций
                            и ТЗ по сайтам, текстам;</li>
                        <li>Оптимизация сайта;</li>
                        <li>Закупка и зачистка ссылок;</li>
                        <li>Умение вести более одного проекта одновременно.</li>
                    </ul>
                </div>
                <div class="vacancy__item">
                    <div class="vacancy__itemHeader">Зароботная плата: </div>
                    <ul>
                        <li>от 40 000 р. до 120 000 р.</li>
                    </ul>
                    <div class="vacancy__itemHeader" style="margin-top: 45px;">Мы предлагаем:</div>
                    <ul>
                        <li>График работы 5/2;</li>
                        <li>Молодой дружный коллектив;</li>
                        <li>Карьерный рост;</li>
                        <li>Профессиональный опыт.</li>
                    </ul>
                </div>
                <div class="vacancy__item">
                    <div class="vacancy__itemHeader">Личные качества:</div>
                    <ul>
                        <li>Активность, коммуникабельность, ответственность;</li>
                        <li>Опыт работы в аналогичной должности
                            не менее 1 года;</li>
                        <li>Нацеленность на результат;</li>
                        <li>Грамотность, усидчивость;</li>
                        <li>Умение брать на себя ответственность
                            за действия и результат.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>